esphome:
  name: test-th-htu21d
  friendly_name: TEST-TH-HTU21D

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8MwfSoW0SBoW3ZXzVdCI/ZkuiHJ75uahekb/3sO5xAw="

ota:
  password: "5fda9b3247d4688c52fbd6358b63ac3d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Th-Htu21D Fallback Hotspot"
    password: "LHW64TH2Xvhn"

captive_portal:
    

dallas:
  - pin: D6

sensor:
#Dallas
  - platform: dallas
    address: 0x89020d9177b37928
    name: "dallas-Temp"

