esphome:
  name: test-th-htu21d
  friendly_name: TEST-TH-HTU21D

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8MwfSoW0SBoW3ZXzVdCI/ZkuiHJ75uahekb/3sO5xAw="

ota:
  password: "5fda9b3247d4688c52fbd6358b63ac3d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Th-Htu21D Fallback Hotspot"
    password: "LHW64TH2Xvhn"

captive_portal:
    
i2c:
  sda: D2
  scl: D1
  frequency: 400kHz
  scan: True

sensor:
# htu21d
  - platform: htu21d
    temperature:
      name: "htu21d-Temp"
      id: htu21d_temp
    humidity:
      name: "htu21d-Humidity"
    address: 0x40
    update_interval: 15s

